<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DataPerkembanganBalitaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_perkembangan_balita')->insert([
            [
                'id_balita' => 1,
                'berat_balita' => 2.8,
                'tinggi_balita' => 48,
                'lingkar_kepala' => 33.5,
                'lingkar_lengan' => 10.2,
                'vaksin' => 'Vitamin A',
                'imunisasi' => 'BCG',
                'tanggal_penimbangan' => '2024-09-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 1,
                'berat_balita' => 3.2,
                'tinggi_balita' => 51,
                'lingkar_kepala' => 34.1,
                'lingkar_lengan' => 10.8,
                'vaksin' => 'Obat Cacing',
                'imunisasi' => 'DPT',
                'tanggal_penimbangan' => '2024-10-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 1,
                'berat_balita' => 3.5,
                'tinggi_balita' => 54,
                'lingkar_kepala' => 34.7,
                'lingkar_lengan' => 11.3,
                'vaksin' => 'Vitamin A',
                'imunisasi' => 'Polio',
                'tanggal_penimbangan' => '2024-11-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 1,
                'berat_balita' => 3.8,
                'tinggi_balita' => 56,
                'lingkar_kepala' => 35.2,
                'lingkar_lengan' => 11.7,
                'vaksin' => 'Tidak Diberikan',
                'imunisasi' => 'Campak',
                'tanggal_penimbangan' => '2024-12-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 1,
                'berat_balita' => 4.0,
                'tinggi_balita' => 58,
                'lingkar_kepala' => 35.8,
                'lingkar_lengan' => 12.1,
                'vaksin' => 'Obat Cacing',
                'imunisasi' => 'DPT',
                'tanggal_penimbangan' => '2025-01-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 2,
                'berat_balita' => 2.9,
                'tinggi_balita' => 49,
                'lingkar_kepala' => 33.7,
                'lingkar_lengan' => 10.3,
                'vaksin' => 'Vitamin A',
                'imunisasi' => 'BCG',
                'tanggal_penimbangan' => '2024-09-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 3,
                'berat_balita' => 3.0,
                'tinggi_balita' => 50,
                'lingkar_kepala' => 34.0,
                'lingkar_lengan' => 10.5,
                'vaksin' => 'Obat Cacing',
                'imunisasi' => 'DPT',
                'tanggal_penimbangan' => '2024-10-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 4,
                'berat_balita' => 3.3,
                'tinggi_balita' => 52,
                'lingkar_kepala' => 34.5,
                'lingkar_lengan' => 10.9,
                'vaksin' => 'Vitamin A',
                'imunisasi' => 'Polio',
                'tanggal_penimbangan' => '2024-11-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 5,
                'berat_balita' => 3.6,
                'tinggi_balita' => 55,
                'lingkar_kepala' => 35.0,
                'lingkar_lengan' => 11.4,
                'vaksin' => 'Tidak Diberikan',
                'imunisasi' => 'Campak',
                'tanggal_penimbangan' => '2024-12-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 6,
                'berat_balita' => 3.9,
                'tinggi_balita' => 57,
                'lingkar_kepala' => 35.6,
                'lingkar_lengan' => 12.0,
                'vaksin' => 'Obat Cacing',
                'imunisasi' => 'DPT',
                'tanggal_penimbangan' => '2025-01-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 7,
                'berat_balita' => 4.1,
                'tinggi_balita' => 59,
                'lingkar_kepala' => 36.0,
                'lingkar_lengan' => 12.3,
                'vaksin' => 'Vitamin A',
                'imunisasi' => 'BCG',
                'tanggal_penimbangan' => '2024-09-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 8,
                'berat_balita' => 4.2,
                'tinggi_balita' => 60,
                'lingkar_kepala' => 36.2,
                'lingkar_lengan' => 12.5,
                'vaksin' => 'Obat Cacing',
                'imunisasi' => 'DPT',
                'tanggal_penimbangan' => '2024-10-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 9,
                'berat_balita' => 4.3,
                'tinggi_balita' => 61,
                'lingkar_kepala' => 36.5,
                'lingkar_lengan' => 12.7,
                'vaksin' => 'Vitamin A',
                'imunisasi' => 'Polio',
                'tanggal_penimbangan' => '2024-11-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 10,
                'berat_balita' => 4.4,
                'tinggi_balita' => 62,
                'lingkar_kepala' => 36.8,
                'lingkar_lengan' => 12.9,
                'vaksin' => 'Tidak Diberikan',
                'imunisasi' => 'Campak',
                'tanggal_penimbangan' => '2024-12-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 11,
                'berat_balita' => 4.5,
                'tinggi_balita' => 63,
                'lingkar_kepala' => 37.0,
                'lingkar_lengan' => 13.1,
                'vaksin' => 'Obat Cacing',
                'imunisasi' => 'DPT',
                'tanggal_penimbangan' => '2025-01-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
            [
                'id_balita' => 12,
                'berat_balita' => 4.6,
                'tinggi_balita' => 64,
                'lingkar_kepala' => 37.2,
                'lingkar_lengan' => 13.3,
                'vaksin' => 'Vitamin A',
                'imunisasi' => 'BCG',
                'tanggal_penimbangan' => '2024-09-01',
                'created_at' => today(),
                'updated_at' => today(),
            ],
        ]);
    }
}
